services:
  api:
    build: .
    container_name: fastapi-application
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
    restart: "no"

  api2:
    build: .
    container_name: fastapi-application-2
    environment:
      PORT: 8082
    ports:
      - '8082:8082'
    restart: "no"
