apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: api
  name: api
spec:
  containers:
    - env:
        - name: PORT
          value: "8080"
      image: api
      name: fastapi-application
      ports:
        - containerPort: 8080
          protocol: TCP
  restartPolicy: Never
