apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: api2
  name: api2
spec:
  containers:
    - env:
        - name: PORT
          value: "8082"
      image: api2
      name: fastapi-application-2
      ports:
        - containerPort: 8082
          protocol: TCP
  restartPolicy: Never
